
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/330px-NumPy_logo_2020.svg.png)

# 넘파이 기초

학습 목표

- Numpy 배열의 기본 개념을 이해합니다.
- 1차원, 2차원, 3차원 배열을 만들 수 있습니다.
- Reshape 기능을 사용해 배열 형태를 바꿀 수 있습니다.
- 인덱싱과 슬라이싱으로 원하는 데이터를 조회할 수 있습니다.
- 배열 사이의 기본적인 연산을 수행할 수 있습니다.

## 1.라이브러리 불러오기

- Numpy 배열을 사용하려면 우선 **numpy** 라이브러리를 불러와야 합니다.
- numpy 라이브러리는 일반적으로 **np** 별칭을 붙여 불러옵니다.

In [1]:
# 라이브러리 불러오기
import numpy as np

## 2.배열 만들기

- 편의를 위해 **Numpy 배열**을 그냥 **배열**이라고 부르기로 합시다.
- 이후 데이터 처리시 배열로 변환해 연산을 하거나, 결과가 배열로 표시되는 경우가 있습니다.
- 배열에 대한 개념은 정확히 파악해 두기를 권고합니다.

### (1) 용어 정의

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

**[용어]**
- axis: 배열의 각 축
- rank: 축의 개수
- shape: 축의 길이, 배열의 크기

  
**[3 x 4 배열의 경우]**
- axis 0 과 axis 1 을 갖는 2차원 배열
- rank 2 array
- shape는 (3, 4)

### (2) 배열 만들기

- **np.array() 함수**를 사용해서 배열을 만듭니다.
- 대부분 **리스트**로부터 배열을 만들거나, 머신러닝 관련 함수 결과값이 배열이 됩니다.

#### 1) 배열 만들기

* **1차원 배열 만들기**

In [2]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]

# 배열로 변환
b1 = np.array(a1)

# 확인
print(b1)

[1 2 3 4 5]


* **2차원 배열 만들기**

In [3]:
# 2차원 리스트
# a2 = [[1.5, 2.5, 3.2], [4.2, 5.7, 6.4]]
a2 = [[1.5, 2.5, 3.2],
      [4.2, 5.7, 6.4]]

# 배열로 변환
b2 = np.array(a2)

# 확인
print(b2)

[[1.5 2.5 3.2]
 [4.2 5.7 6.4]]


* **3차원 배열 만들기**

In [4]:
# 3차원 리스트
# a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
a3 = [[[1, 3, 1],
       [4, 7, 6],
       [8, 3, 4]],
      [[6, 2, 4],
       [8, 1, 5],
       [3, 5, 9]]]

# 배열로 변환
b3 = np.array(a3)

# 확인
print(b3)

[[[1 3 1]
  [4 7 6]
  [8 3 4]]

 [[6 2 4]
  [8 1 5]
  [3 5 9]]]


#### 2) 배열 정보 확인

- 배열 정보를 확인하는 다음 속성들을 기억하시기 바랍니다.
- 특히 shape 속성은 이후에도 많이 사용될 것입니다.

<img src='https://github.com/DA4BAM/image/blob/main/1,2,3%20%EC%B0%A8%EC%9B%90.png?raw=true' width=800 align="left"/>

* **차원 확인**
    - ndim 속성으로 배열 차원을 확인합니다.

In [5]:
# 차원 확인
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

1
2
3


* **형태(크기) 확인**
    - shape 속성으로 배열 형태를 확인합니다.
    - 결과는 다음과 같은 형태의 튜플로 표시됩니다.
        - 1차원: (x, )
        - 2차원: (x, y)
        - 3차원: (x, y, z)
    - 앞에서 부터 axis 0, axis 1, axis 2의 크기를 의미합니다.

In [6]:
# 형태(크기) 확인
print(b1.shape)
print(b2.shape)
print(b3.shape)

(5,)
(2, 3)
(2, 3, 3)


* **요소 자료형 확인**
    - dtype 속성으로 배열에 포함된 요소들의 자료형을 확인합니다.
    - 배열은 한 가지 자료형만 가질 수 있다는 특징이 있습니다.

In [7]:
# 요소 자료형 형식 확인
print(b1.dtype)
print(b2.dtype)
print(b3.dtype)

int64
float64
int64


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

[문2] 다음에 주어진 데이터를 갖는 1차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요.

In [8]:
# 10, 11, 12, 13, 14, 15
d = [10, 11, 12 , 13, 14, 15]

# 배열 만들기
a1 = np.array(d)

# 확인
print(a1)

# 정보 확인
print(a1.ndim)
print(a1.shape)
print(a1.dtype)

[10 11 12 13 14 15]
1
(6,)
int64


[문3] 다음에 주어진 리스트를 요소로 갖는 2차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요

In [9]:
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

# 배열 만들기
a2 = np.array(a)

# 확인
print(a2)

# 정보 확인
print(a2.ndim)
print(a2.shape)
print(a2.dtype)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
2
(3, 4)
int64


#### 3) Reshape

- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있습니다.
- 배열에 포함된 **요소가 사라지지 않는 형태**라면 자유롭게 변환할 수 있습니다.
- (3, 4) → (2, 6) → (4, 3) → (12, 1) → (6, 2) 등등 요소 개수만 변하지 않으면 됩니다.

In [10]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]]


* **(2, 3) → (3, 2)**

In [11]:
# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3, 2)

# 확인
print(b)

[[1 2]
 [3 4]
 [5 6]]


* **(2, 3) → (6,)**

In [12]:
# 1차원 배열로 Reshape
# c = a.reshape(6,)
c = a.reshape(6)

# 확인
print(c)

[1 2 3 4 5 6]


* **-1의 편리성**

    - **(*m*, -1)** 또는 **(-1, *n*)** 처럼 사용해 행 또는 열 크기 한 쪽만 지정할 수 있습니다.

In [13]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]]


In [14]:
# reshape(m, -1) 형태로 지정하여 Reshape 가능
print(a.reshape(1, -1))
print()

print(a.reshape(2, -1))
print()

print(a.reshape(3, -1))
print()

#print(a.reshape(4, -1))
#print(a.reshape(5, -1))

print(a.reshape(6, -1))

[[1 2 3 4 5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음에 주어진 배열의 형태(shape)를 확인한 후 요구되는 형태로 바꿔 보세요.

In [15]:
# 배열 만들기
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

# 배열 형태 확인
print(a.shape)

# (4, ?))형태의 2차원 배열
a1 = a.reshape(4,-1)

# 확인
print(a1.shape)

# (2, ?) 형태의 2차원 배열
a2 = a.reshape(2,-1)

# 확인
print(a2.shape)

(3, 4)
(4, 3)
(2, 6)


## 3.배열 인덱싱과 슬라이싱

- 지금까지 다룬 자료형들 보다 배열 인덱싱과 슬라이싱이 조금 어렵습니다.

### (1) 인덱싱

- 1차원 배열은 리스트와 방법이 같으므로 설명을 생략합니다.
- **배열[행, 열]** 형태로 특정 위치의 요소를 조회합니다.
- **배열[[행1,행2,..], :]** 또는 **배열[[행1,행2,..]]** 형태로 특정 행을 조회합니다.
- **배열[:, [열1,열2,...]]** 형태로 특정 열을 조회합니다.
- **배열[[행1,행2,...], [열1,열2,...]]** 형태로 특정 행의 특정 열을 조회합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.png?raw=true' width=800 align="left"/>

In [16]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a[0]

array([1, 2, 3])

In [17]:
a[[0],[1]]

array([2])

#### **1) 요소 조회**

In [18]:
# 첫 번째 행, 두 번째 열 요소 조회
print(a[0, 1])

2


#### **2) 행 조회**

In [20]:
# 첫 번째, 두 번째 행 조회
# print(a[[0, 1], :])
print(a[[0, 1]])

[[1 2 3]
 [4 5 6]]


In [21]:
# 첫 번째, 두 번째, 세 번째 행 조회
# print(a[[0, 1, 2], :])
print(a[[0, 1, 2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### **3) 열 조회**

In [22]:
# 첫 번째, 두 번째 열 조회
print(a[:, [0, 1]])

[[1 2]
 [4 5]
 [7 8]]


#### **4) 행, 열 조회**

In [23]:
# 배열 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# 두 번째 행 두 번째 열의 요소 조회
print(a[[1], [1]])

[5]


In [25]:
# 세 번째 행 두 번째 열의 요소 조회
print(a[[2], [1]])

[8]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [26]:
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

[문1] 16

In [27]:
a[1,1]

16

[문2] [19 20 21 22]

In [28]:
a[2]

array([19, 20, 21, 22])

numpy 배열에서 특정 행 또는 열의 값을 추출하면 해당 부분이 numpy 형태로 변환되기 때문에 array([...]) 형태로 출력됩니다. 만약 numpy 배열에서 array 표시 없이 특정 행 또는 열만의 값을 출력하고 싶다면, 다음과 같은 방법을 사용하면 됩니다.

In [30]:
# 1. tolist() 메서드 사용

# numpy 배열의 2번째(인덱스 2) 행을 리스트로 변환
row = a[2].tolist()
print(row)  # 출력: [19, 20, 21, 22]

[19, 20, 21, 22]


In [31]:
# 2. * 연산자 사용 (Unpacking)

# numpy 배열의 2번째(인덱스 2) 행을 언패킹하여 출력
print(*a[2])  # 출력: 19 20 21 22 (리스트의 각 요소를 개별적으로 출력)

19 20 21 22


[문3] [13  17  21]

In [29]:
a[:,2]

array([13, 17, 21])

### (2) 슬라이싱

- **배열[행1:행N,열1:열N]** 형태로 지정해 그 위치의 요소를 조회합니다.
- 조회 결과는 **2차원 배열**이 됩니다.
- 마지막 **범위 값은 대상에 포함되지 않습니다.**
- 즉, **배열[1:M, 2:N]**이라면 1 ~ M-1행, 2 ~ N-1열이 조회 대상이 됩니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B12.png?raw=true' width=800 align="left"/>

In [32]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# 첫 번째 ~ 두 번째 행 조회
# print(a[0:2, :])
print(a[0:2])

[[1 2 3]
 [4 5 6]]


In [34]:
# 첫 번째 행, 첫 번째 ~ 두 번째 열 조회
print(a[0, 0:2])

[1 2]


In [35]:
# 첫 번째 ~ 세 번째 행, 두 번째 ~ 세 번째 열 조회
print(a[0:3, 1:3])

[[2 3]
 [5 6]
 [8 9]]


In [36]:
# 두 번째 ~ 끝 행, 두 번째 ~ 끝 열 조회
print(a[1:, 1:])

[[5 6]
 [8 9]]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [37]:
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

[문1]   

[[12]  
[16]  
[20]]

In [38]:
a[:,[1]]

array([[12],
       [16],
       [20]])

[문2]

[[16  17]  
 [20  21]]

In [39]:
a[1:3,1:3]

array([[16, 17],
       [20, 21]])

### (3) 조건 조회

- **조건에 맞는 요소를 선택**하는 방식이며, **불리안 방식**이라고 부릅니다.
- 조회 결과는 **1차원 배열**이 됩니다.

In [40]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]


In [42]:
score >= 90

array([[False,  True, False, False,  True, False],
       [False, False,  True, False,  True, False]])

- **배열[조건]** 형태로 해당 조건에 맞는 요소만 조회합니다.

In [41]:
# 요소 중에서 90 이상인 것만 조회
print(score[score >= 90])

[91 93 96 91]


- 검색 조건을 변수로 선언해 사용할 수 있습니다.

In [43]:
# 요소 중에서 90 이상인 것만 조회
condition = score >= 90
print(score[condition])

[91 93 96 91]


- 여러 조건을 **&** 와 **|** 로 연결하여 조회할 수 있습니다.

In [44]:
# 모든 요소 중에서 90 이상 95 미만인 것만 조회
print(score[(score >= 90) & (score <= 95)])

[91 93 91]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

[문1] 다음 배열에서 80 미만의 데이터만 추출하시오.

In [47]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 80 미만 데이터 조회
print(score[score < 80])

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]
[78 65 79 73]


[문2] 다음 배열에서 짝수만 추출해 보세요.

In [46]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 짝수만 조회
print(score[score % 2 == 0])

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]
[78 84 82 96]


## 4.배열 연산

- 배열 사이의 더하기, 빼기, 곱하기, 나누기 등은 이해하기 쉽습니다.
- 하지만 행렬 곱, 행렬 합등의 연산은 약간의 수학적 지식이 필요합니다.
- 행렬 연산은 선형 대수를 위한 것이므로 설명을 생략합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0.png?raw=true' width=600 align="left"/>

In [48]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### **(1) 배열 사칙연산**

* **더하기**

    - \+ 또는 **np.add()** 함수를 사용합니다.

In [49]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


* **빼기**

    - \- 또는 **np.subtract()** 함수를 사용합니다.

In [50]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


* **곱하기**

    - \* 또는 **np.multiply()** 함수를 사용합니다.

In [51]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


* **배열 나누기**

    - \/ 또는 **np.divide()** 함수를 사용합니다.

In [52]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


* **지수 연산**

    - \** 또는 **np.power()** 함수를 사용합니다.

In [53]:
# 배열 y 제곱
print(x ** y)

# 또는
print(np.power(x, y))

[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]


In [54]:
# 배열 제곱
print(x ** 2)

[[ 1  4]
 [ 9 16]]


### **(2) 배열 집계**

- np.sum(), 혹은 array.sum()
    * axis = 0 : 열 기준 집계
    * axis = 1 : 행 기준 집계
    * 생략하면 : 전체 집계
- 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()

In [55]:
# array를 생성합니다.
a = np.array([[1,5,7],[2,3,8]])
print(a)

[[1 5 7]
 [2 3 8]]


In [56]:
# 전체 집계
print(np.sum(a))

# 열기준 집계
print(np.sum(a, axis = 0))

# 행기준 집계
print(np.sum(a, axis = 1))

26
[ 3  8 15]
[13 13]


### **(3) 자주 사용되는 함수들**

#### **1) np.argmax(), np.argmin()**

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4_argmin.png?raw=true' width=800 align="left"/>

In [57]:
print(a)
# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(a))

# 행 방향 최대값의 인덱스
print(np.argmax(a, axis = 0))

# 열 방향 최대값의 인덱스
print(np.argmax(a, axis = 1))


[[1 5 7]
 [2 3 8]]
5
[1 0 1]
[2 2]


#### **2) np.where**

* np.where(조건문, True일때 값, False일 때 값)

In [58]:
# 선언
a = np.array([1,3,2,7])

# 조건
np.where(a > 2, 1, 0)

array([0, 1, 0, 1])

## 5.복습문제

1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [59]:
# 라이브러리 불러오기
import numpy as np

2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [60]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기
arr = [[1,2,3],
       [4,5,6],
       [7,8,9],
       [10,11,12]]

np_arr = np.array(arr)

# 확인
print(np_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

In [61]:
# 배열 크기 확인
print(np_arr.shape)

(4, 3)


4) np_arr 배열을 아래 주어진 3 X 4 형태의 배열로 바꿔서 np_02 배열로 선언하고 확인하세요.

In [63]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# 형태 변경
np_02 = np_arr.reshape(3, 4)

# 확인
print(np_02)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


5) np_arr 배열의 세 번째 행의 요소들을 조회하세요.

In [64]:
# [7 8 9] 조회
print(np_arr[2])

[7 8 9]


6) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.

In [65]:
# 10 곱하기
print(np.multiply(np_arr, 10))

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


7) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.  
[ 8  9 10 11 12]

In [66]:
# 조건 조회
np_x = np_arr.reshape(12,)
print(np_x[np_x > 7])

[ 8  9 10 11 12]


8) 7번 실습에서 선택된 요소들의 값만 각각 2배로 만드세요.

In [67]:
# 조회 결과에 대한 연산
np.where(np_arr > 7, np_arr * 2, np_arr)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 16, 18],
       [20, 22, 24]])

9) np_arr 배열의 값을 조회해서 변경된 내용을 확인해 보세요.

In [68]:
# 원본 배열 확인
print(np_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


10) np_arr 배열의 요소들 중에서 3의 배수는 1, 아니면 0인 배열을 만들고 조회하시오.

In [69]:
np.where(np_arr % 3 == 0, 1, 0)

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

11) np_arr의 전체 평균, 열별 평균, 행별 평균을 구하세요.

In [70]:
print(np_arr.mean())
print(np_arr.mean(axis=0))
print(np_arr.mean(axis=1))

6.5
[5.5 6.5 7.5]
[ 2.  5.  8. 11.]
